### ISSUE TITLE
Channel not responding and not playing

### ISSUE THREAD

**Issue by IJ08** [Twoure/9anime.bundle#15]
Working yesterday, now everytime I try to play a video from "NEWEST update" I get channel not responding.

[9anime logs.zip](https://github.com/Twoure/9anime.bundle/files/1048993/9anime.logs.zip)

**Comment by IJ08** [comment]
Updating logs after updating the PMS channel for 9anime.

[9anime logs.zip](https://github.com/Twoure/9anime.bundle/files/1049016/9anime.logs.zip)

Noticed some videos play while others are not. I replicated both scenarios in the logs. Last video was the one that failed to play

**Comment by Twoure** [comment]
Thanks for the heads up _(and logs)_, think I may see the issue.  Will work on a fix.

**Comment by IJ08** [comment]
Thanks as usual!

**Comment by Twoure** [comment]
Should be fixed in https://github.com/Twoure/9anime.bundle/commit/544609e024cffcd0b5a1a4cc3a1241bf942f8ffc.  Stick with default `9anime.1` as video server and should be okay.

**Comment by IJ08** [comment]
I updated to the dev branch and restarted PMS.

1. Cleared DATAHTTP
2. Set server to 9anime.1 -> Server1 logs
3. Set server to 9anime.2 -> Server 2 logs

Some videos play others do not. Both server 1 and 2 have the same videos play and not play. I tested with another restart as well after changing to server 1 again and reseting DATAHTTP. All details are in attached logs

[9anime logs.zip](https://github.com/Twoure/9anime.bundle/files/1049543/9anime.logs.zip)

**Comment by Twoure** [comment]
Sorry but the logs included do not show any errors.  The logs seem to be only for the `9anime.1` server, so perhaps they are old logs?

**Comment by IJ08** [comment]
Sorry bout that, not sure what happened. I repeated the steps and sometimes I get channel not responding. And videos are not playing.

Attached. Includes tests from server1 and server2

[Logs.zip](https://github.com/Twoure/9anime.bundle/files/1049932/Logs.zip)

**Comment by Twoure** [comment]
Okay, so looks like a few things are happening.

1. `.to` site is having connection issues _(i.e. site issue not channel)_
    - `502 Server Error: Bad Gateway for url: https://9anime.to`
    - `522 Server Error: Origin Connection Time-out for url: https://9anime.to` 
2. Site is returning **Dead** video links, in channel and in normal web browser _(again site issue)_
3. Site is returning **NO** video links.  It's returning an `unknown` API error _(...again site issue, not channel)_
    - ![](http://i.imgur.com/pImFD6w.jpg)
4. JRE Error: This is a _know_ limitation/error for the channel, and can be fixed by going back and foreword in channel navigation.
    - `ProgramError: TypeError: _[_] is not a function`
5. https://twitter.com/9animeto/status/870867831256080385
6. https://www.reddit.com/r/9anime/comments/6f3cf3/do_not_post_duplicate_posts/

I added their 2nd domain to the prefs in https://github.com/Twoure/9anime.bundle/commit/94e1c4af7e405d1584a5ac5f2af375cdb6c8c7f7.  You can try and see if it helps with the connection errors, but in the end we'll have to wait for the main sites to work out their server issues.

**Edit:** FYI: Openload server should work, that is if the 9anime sites lets you connect.

**Comment by IJ08** [comment]
Got it. I'll stick to current dev branch. Is the newer dev branch with pref domain manual change of domain config? or auto-discover/switch if it fails on primary?

**Comment by Twoure** [comment]
For now, It's just a simple global user switch, located within this channel's preferences.

**Comment by IJ08** [comment]
Thanks as usual!  I'll monitor the channel regularly and remain at current

**Comment by IJ08** [comment]
All the F* servers are out, only servers I see now are MYCLOUD and Openload. Does the 9anime dev latest account for the new MYCLOUD servers ? I am getting errors playing vids via the channel

[Logs.zip](https://github.com/Twoure/9anime.bundle/files/1065325/Logs.zip)

**Comment by Twoure** [comment]
> Does the 9anime dev latest account for the new MYCLOUD servers ?

Nope.  Working on a fix.

**Comment by Twoure** [comment]
> All the F* servers are out, only servers I see now are MYCLOUD and Openload. Does the 9anime dev latest account for the new MYCLOUD servers ? I am getting errors playing vids via the channel

Should be fixed in https://github.com/Twoure/9anime.bundle/commit/6ce7aff245ef6769f2a0a6457281d8891b8452fa.  Download/install latest `dev` branch, then restart PMS for changes to fully apply.

**Comment by IJ08** [comment]
Cool, just tested it works.
